//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Functions -------------------------

// From module:   /home/user/level07/level07.c
// Address range: 0x8048514 - 0x80485af
// Line range:    6 - 24
int main(int argc, char ** argv) {
    // 0x8048514
    char * v1;
    char * buffer = v1; // bp-28
    int32_t v2;
    int32_t gid = v2; // bp-24
    int32_t v3;
    int32_t uid = v3; // bp-20
    gid = getegid();
    uid = geteuid();
    setresgid(gid, gid, gid);
    setresuid(uid, uid, uid);
    buffer = NULL;
    char * env_val = getenv("LOGNAME"); // 0x8048576
    asprintf(&buffer, "/bin/echo %s ", env_val);
    return system(buffer);
}

// --------------- Dynamically Linked Functions ---------------

// int asprintf(char ** restrict ptr, const char * restrict fmt, ...);
// __gid_t getegid(void);
// char * getenv(const char * name);
// __uid_t geteuid(void);
// int setresgid(__gid_t rgid, __gid_t egid, __gid_t sgid);
// int setresuid(__uid_t ruid, __uid_t euid, __uid_t suid);
// int system(const char * command);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected language: C
// Detected functions: 1
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-11-30 00:01:05
